name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # Se actualiza 1 vez al día
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_V2_NUEVO }}
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 3
          plugin_languages_sections: most-used
          config_timezone: America/Argentina/Buenos_Aires
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          theme: radical
